### ISSUE TITLE
Nothing happen when droping image

### ISSUE THREAD

**Issue by ZeroX-DG** [ZeroX-DG/limus#1]
The image is not recognized when being dropped instead of being selected using the browse button

**Comment by djibe** [comment]
Same when using Browse file button

**Comment by ZeroX-DG** [comment]
@djibe can you open another issue for that and describe how you can reproduce the bug? Because I can't reproduce it on my machine.

**Comment by ZeroX-DG** [comment]
Fixed in https://github.com/ZeroX-DG/limus/commit/dbbce0ffb06614168a01adc88d4712c44da391d4
